### ISSUE TITLE
Block height stoped on 23096664

### ISSUE THREAD

**Issue by DreamXzxy** [Deerfi/flashloan-info#12]
![image](https://user-images.githubusercontent.com/17998878/105335393-f553ab00-5c12-11eb-83cf-0404e4363657.png)

**Comment by TT1943** [comment]
It is because there is some issue in https://thegraph.com/explorer/subgraph/deerfi/kovan-deer?selected=logs

I will fixed it.

**Comment by TT1943** [comment]
Fixed at https://github.com/Deerfi/flashloan-v1-subgraph/commit/b16edc6ea2fdc4a46cca4bfa62a2316dc763f57d
