### ISSUE TITLE
Make sure pool page works

### ISSUE THREAD

**Issue by TT1943** [Deerfi/flashloan-info#6]

**Comment by DreamXzxy** [comment]
1.Refine code and fix some data errors
https://github.com/Deerfi/flashloan-info/pull/21
2.Fix add liquidity on t the pool page
https://github.com/Deerfi/flashloan-info/pull/26
![image](https://user-images.githubusercontent.com/17998878/105635735-77580400-5e9f-11eb-980b-b9a25a7b6775.png)
3.Fix transactions on the pool page
https://github.com/Deerfi/flashloan-info/pull/23
![image](https://user-images.githubusercontent.com/17998878/105635749-9060b500-5e9f-11eb-84ce-f5ed5f4b5bfa.png)
