### ISSUE TITLE
Change DoubleTokenLogo to TokenLogo in /accounts and /pools

### ISSUE THREAD

**Issue by TT1943** [Deerfi/flashloan-info#9]
![image](https://user-images.githubusercontent.com/711206/105283133-b2d39500-5b64-11eb-917e-e82d21d560b8.png)

**Comment by DreamXzxy** [comment]
https://github.com/Deerfi/flashloan-info/pull/13

**Comment by TT1943** [comment]
https://github.com/Deerfi/flashloan-info/pull/17
